name: "Add PR Comment"
description: "Add a comment to a pull request"
inputs:
  message:
    description: "The message to print."
    required: true
  repo-token:
    description: "A GitHub token for API access."
    required: false
  repo-token-user-login:
    description: "A user login associated with your token, for temporary repo tokens this is `github-actions[bot]`."
    required: false
  allow-repeats:
    description: "Allow messages to be repeated."
    required: false
    default: "false"
branding:
  icon: message-circle
  color: purple
runs:
  using: "node12"
  main: "dist/index.js"
