name: "Add PR Comment"
description: "Add a comment to a PR"
inputs:
  message:
    description: "the message to print"
    required: true
  repo-token:
    description: "a github token for API access"
    required: true
  allow-repeats:
    description: "allow messages to be repeated"
    required: false
    default: "false"
branding:
  icon: message-circle
  color: purple
runs:
  using: "node12"
  main: "dist/index.js"
