name: "Add PR Comment"
description: "Add a comment to a PR"
inputs:
  msg:
    description: "the message to print"
    required: true
  repo-token:
    description: "a github token for API access"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
