name: ci

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions: {}

jobs:
  pr-title:
    name: pr title
    runs-on: ubuntu-slim
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: unit tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: setup node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: ".node-version"

      - name: install dependencies
        run: |
          npm ci

      - name: lint code
        run: |
          npm run lint

      - name: build action
        run: |
          npm run build

      - name: run tests
        run: |
          npm test

  dogfood:
    name: dogfood
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: setup node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: ".node-version"

      - name: install dependencies
        run: |
          npm ci

      - name: Build action
        run: |
          npm run build

      - uses: ./
        with:
          preformatted: true
          message-id: path
          message-path: |
            .github/test/file-*.txt

      - uses: ./
        with:
          message-id: text
          message: |
            **Hello**
            🌏
            !

      - uses: ./
        with:
          message-id: text
          find: |
            Hello
            🌏
          replace: |
            Goodnight
            🌕
